=== openeoe/EVE-ICBAM/manager/project/resource/mi/model/model.dtd
<!ENTITY % Name "NAME CDATA #REQUIRED">
<!ENTITY % Type "TYPE (boolean|byte|char|string|int|float|long|double)">
<!ENTITY % ClassOrigin "CLASSORIGIN CDATA">
<!ENTITY % Parent "PARENT CDATA #REQUIRED">
<!ENTITY % Maxlen "MAXLEN CDATA #IMPLIED">

<!ELEMENT GKES:MODEL (GKES:CORE_MODEL,GKES:EXT_MODEL*)>
<!ATTLIST GKES:MODEL	
	xmlns:GKES CDATA #REQUIRED
	%Name;
	NASVERSION CDATA #REQUIRED	
	DTDVERSION CDATA #REQUIRED>

<!ELEMENT GKES:CORE_MODEL (GKES:MODELCLASS,GKES:MODELASSOCIATION)>

<!ELEMENT GKES:MODELCLASS (GKES:ROOTCLASS,GKES:CLASS+)>
<!ELEMENT GKES:ROOTCLASS (GKES:PROPERTY)*>
<!ATTLIST GKES:ROOTCLASS
	%Name;
	ISABSTRACT (true|false) #IMPLIED	
	ISCORE		(true|false) #IMPLIED
>
<!ELEMENT GKES:CLASS (GKES:PROPERTY)*>
<!ATTLIST GKES:CLASS	
	%Name;	
	%Parent;	
	ISABSTRACT (true|false) #IMPLIED	
	ISCORE		(true|false) #IMPLIED
	ISINDICATION (true|false) #IMPLIED
>

<!ELEMENT GKES:PROPERTY (GKES:VALUE)?>
<!ATTLIST GKES:PROPERTY	
	%Name;	
	%Type;	#REQUIRED	
	%ClassOrigin; #REQUIRED	
	%Maxlen;
	ISKEY (true|false) #IMPLIED	
	ISINDICATION (true|false) #IMPLIED
	ISLIST (true|false) #IMPLIED 	
	ISOVERRIDE (true|false) #IMPLIED
	ISOBJECT (true|false) #IMPLIED
    NOTNULL (true|false) #IMPLIED>

<!ELEMENT GKES:VALUE (#PCDATA)>
<!ELEMENT GKES:MODELASSOCIATION (GKES:ASSOCIATION)*>
<!ELEMENT GKES:ASSOCIATION (GKES:FIRSTCLASS,GKES:SECONDCLASS)>
<!ATTLIST GKES:ASSOCIATION
	%Name;
	TYPE 	(CONTAINMENT|REFERENCE) #REQUIRED
	ISCORE (true|false) #IMPLIED
	ISINDICATION (true|false) #IMPLIED
>
<!ELEMENT GKES:FIRSTCLASS EMPTY>
<!ATTLIST GKES:FIRSTCLASS
	%Name;
	ROLE  CDATA #REQUIRED
	MULTIPLICITY CDATA #REQUIRED >
<!ELEMENT GKES:SECONDCLASS EMPTY>
<!ATTLIST GKES:SECONDCLASS
	%Name;
	ROLE  CDATA #REQUIRED
	MULTIPLICITY CDATA #REQUIRED >
<!ELEMENT   GKES:EXT_MODEL EMPTY>
    <!ATTLIST   GKES:EXT_MODEL
        xmlns:xlink CDATA   #FIXED  "http://www.w3.org/1999/xlink/namespace/"
        xlink:type  (simple|extended|locator|arc)   #FIXED "simple"
        xlink:href  CDATA   #REQUIRED
        xlink:role  CDATA   #REQUIRED
        xlink:title CDATA   #IMPLIED
        xlink:show  (new|parsed|replace|embed) "embed"
        xlink:actuate (user|auto) "auto"
    >

=== openeoe/EVE-ICBAM/manager/project/resource/mi/model/core_model.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
<!DOCTYPE GKES:MODEL SYSTEM "resource/mi/model/model.dtd">
-->
<GKES:MODEL
	xmlns:GKES=http://www.gkes.co.kr"
	NAME="GKES" NASVERSION="1.0" DTDVERSION="1.0">
<GKES:CORE_MODEL>
	<!-- Class Definition -->
	<GKES:MODELCLASS>
		<!--
			- 관리 대상 클래스의 최상위 클래스이다.

			- id : 클래스의 instance을 생성할때 키가 되는 값이다.
			- containment : instance들의 containment 관계을 저장하고 있는
			  변수이다. 저장 방식을 instanceName@instanceName@instanceName
			  뒤에 있는 instanceName의 instance가 포함관계의 최상위 instance임
		-->
		<GKES:ROOTCLASS NAME="ManagedElement" ISABSTRACT="true" ISCORE="true">
			<GKES:PROPERTY NAME="id" TYPE="string" CLASSORIGIN="ManagedElement"
					ISKEY="true" MAXLEN="100"/>
			<GKES:PROPERTY NAME="containment" TYPE="string"
					CLASSORIGIN="ManagedElement" MAXLEN="500"/>
			</GKES:ROOTCLASS>
		<!--
			- 시스템 관리 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="ManagedSystemElement" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- History 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="History" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- Statistics 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="Statistics" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- StatisticsAlert 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="StatisticsAlert" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- StatisticsLabel 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="StatisticsLabel" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- StatisticsAvail 대상의 최상위 클래스이다.
		-->
		<GKES:CLASS NAME="StatisticsAvail" ISABSTRACT="true"
				PARENT="ManagedElement" ISCORE="true"/>

		<!--
			- SNMP TRAP의 Variable Bind을 나타내는 클래스이다.

			- oid : SNMP Object ID
			- value : oid의 value
		-->
		<GKES:CLASS NAME="VBCondition" ISCORE="true"
				PARENT="ManagedElement">
			<GKES:PROPERTY NAME="oid" TYPE="string"
					CLASSORIGIN="VBCondition" MAXLEN="100"/>
			<GKES:PROPERTY NAME="value" TYPE="string"
					CLASSORIGIN="VBCondition" MAXLEN="20"/>
		</GKES:CLASS>

		<!--
			- 관대상의 Group을 나타내는 Class이다.

			- name : Group의 이름
		-->
		<GKES:CLASS NAME="Group" ISABSTACT="true" ISCORE="true"
				PARENT="ManagedElement">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="Group" MAXLEN="50"/>
		</GKES:CLASS>

		<!--
			- 사람을 나타내는 클래스이다.

			- name : 사람의 이름
			- descr : 설명
		-->
		<GKES:CLASS NAME="Person" ISABSTRACT="true" ISCORE="true"
				PARENT="ManagedElement">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="Person" MAXLEN="50"/>
			<GKES:PROPERTY NAME="descr" TYPE="string"
					CLASSORIGIN="Person" MAXLEN="50"/>
		</GKES:CLASS>

		<!--
			- 관리 시스템 및 관리 대상에 대한 설정을 나타내는 클래스이다.
		-->
		<GKES:CLASS NAME="Setting" ISABSTRACT="true" ISCORE="true"
				PARENT="ManagedElement"/>

		<!--
			- Rule

			- faultClassName : 관리자가 정의한 faultClass의 이름
		-->
		<GKES:CLASS NAME="Rule" ISCORE="true" PARENT="ManagedElement"
				ISABSTRACT="true">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="Rule" MAXLEN="50"/>
			<GKES:PROPERTY NAME="faultClassName" TYPE="string"
					CLASSORIGIN="Rule" MAXLEN="50"/>
			<GKES:PROPERTY NAME="subject" TYPE="string"
					CLASSORIGIN="Rule" MAXLEN="20"/>
			<GKES:PROPERTY NAME="moClass" TYPE="string"
					CLASSORIGIN="Rule" MAXLEN="255"/>
			<GKES:PROPERTY NAME="severity" TYPE="int"
					CLASSORIGIN="Rule" />
			<GKES:PROPERTY NAME="message" TYPE="string"
					CLASSORIGIN="Rule" MAXLEN="255"/>
		</GKES:CLASS>

		<!--
			- Rule에 해당하는 조취를 나타내는 클래스이다.

			- name :
			- subject :
			- type :
			- script :
		-->
		<GKES:CLASS NAME="Action" ISCORE="true" PARENT="ManagedElement">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="Action" MAXLEN="50"/>
			<GKES:PROPERTY NAME="subject" TYPE="int"
					CLASSORIGIN="Action" />
			<GKES:PROPERTY NAME="type" TYPE="int"
					CLASSORIGIN="Action" />
			<GKES:PROPERTY NAME="script" TYPE="string"
					CLASSORIGIN="Action" MAXLEN="255"/>
			<GKES:PROPERTY NAME="descr" TYPE="string"
					CLASSORIGIN="Action" MAXLEN="255"/>
		</GKES:CLASS>

		<!--
			- Logical Element Class
		-->
		<GKES:CLASS NAME="LogicalElement" ISABSTRACT="true" ISCORE="true"
				PARENT="ManagedSystemElement"/>

		<!--
			- Logical Device Class
		-->
		<GKES:CLASS NAME="LogicalDevice" ISABSTRACT="true" ISCORE="true"
				PARENT="ManagedSystemElement">
			<GKES:PROPERTY NAME="perfAll" TYPE="int"
					CLASSORIGIN="ComputerSystem"/>
		</GKES:CLASS>

		<!--
			- System class
		-->
		<GKES:CLASS NAME="System" ISABSTRACT="false" ISCORE="true"
				PARENT="ManagedSystemElement">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="sysName" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="sysDescr" TYPE="string"
					CLASSORIGIN="System" MAXLEN="255"/>
			<GKES:PROPERTY NAME="sysObjectId" TYPE="string"
					CLASSORIGIN="System" MAXLEN="50"/>
			<GKES:PROPERTY NAME="sysClass" TYPE="string"
					CLASSORIGIN="System" MAXLEN="40"/>
			<GKES:PROPERTY NAME="sysLocation" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="vendor" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="model" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="admin" TYPE="string"
					CLASSORIGIN="System" MAXLEN="100"/>
			<GKES:PROPERTY NAME="ipAddr" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="networkStatus" TYPE="int"
					CLASSORIGIN="System" ISINDICATION="true">
				<GKES:VALUE>1</GKES:VALUE>
			</GKES:PROPERTY>
			<GKES:PROPERTY NAME="SNMPStatus" TYPE="int"
					CLASSORIGIN="System" ISINDICATION="true">
				<GKES:VALUE>1</GKES:VALUE>
			</GKES:PROPERTY>

			<GKES:PROPERTY NAME="hasNASAgent" TYPE="boolean"
					CLASSORIGIN="System">
				<GKES:VALUE>false</GKES:VALUE>
			</GKES:PROPERTY>

			<GKES:PROPERTY NAME="responseTime" TYPE="int"
					CLASSORIGIN="System" ISINDICATION="true">
				<GKES:VALUE>0</GKES:VALUE>
			</GKES:PROPERTY>
			<GKES:PROPERTY NAME="osType" TYPE="string"
					CLASSORIGIN="System" MAXLEN="50"/>
			<GKES:PROPERTY NAME="osVersion" TYPE="string"
					CLASSORIGIN="System" MAXLEN="50"/>
			<GKES:PROPERTY NAME="cpuUsage" TYPE="double"
					CLASSORIGIN="System" ISINDICATION="true"/>
			<GKES:PROPERTY NAME="memoryUsage" TYPE="double"
					CLASSORIGIN="System" ISINDICATION="true"/>
			<GKES:PROPERTY NAME="FoMemoryUsage" TYPE="double"
					CLASSORIGIN="System" ISINDICATION="true"/>
			<GKES:PROPERTY NAME="sgid" TYPE="string"
					CLASSORIGIN="System" MAXLEN="64"/>
			<GKES:PROPERTY NAME="task" TYPE="string"
					CLASSORIGIN="System" MAXLEN="3"/>
			<GKES:PROPERTY NAME="historyStatus" TYPE="int"
					CLASSORIGIN="System" ISINDICATION="true"/>
			<GKES:PROPERTY NAME="purchaseDate" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="purchasePrice" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="contractNumber" TYPE="string"
					CLASSORIGIN="System" MAXLEN="50"/>
			<GKES:PROPERTY NAME="contractPrice" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="purchaseProcess" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="acquisitionDate" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="communityString" TYPE="string"
					CLASSORIGIN="System" MAXLEN="20"/>
			<GKES:PROPERTY NAME="degree" TYPE="int"
					CLASSORIGIN="System" />
			<GKES:PROPERTY NAME="memo" TYPE="string"
					CLASSORIGIN="System" MAXLEN="4000"/>
			<GKES:PROPERTY NAME="isAlert" TYPE="boolean"
					CLASSORIGIN="System" >
				<GKES:VALUE>true</GKES:VALUE>
			</GKES:PROPERTY>
			<GKES:PROPERTY NAME="relatedEquip" TYPE="string"
					CLASSORIGIN="System" MAXLEN="255"/>

			<GKES:PROPERTY NAME="authUser" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="authProtocol" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="authPassword" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="privProtocol" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="privPassword" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>

			<GKES:PROPERTY NAME="reservation1" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="reservation2" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="reservation3" TYPE="string"
					CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="serialNumber" TYPE="string"
								CLASSORIGIN="System" MAXLEN="30"/>
			<GKES:PROPERTY NAME="isExternal" TYPE="int"
					CLASSORIGIN="System">
					<GKES:VALUE>0</GKES:VALUE>
			</GKES:PROPERTY>
		</GKES:CLASS>

		<!--
			- Service class
		-->
		<GKES:CLASS NAME="Service" ISABSTRACT="true" ISCORE="true"
				PARENT="ManagedSystemElement">
			<GKES:PROPERTY NAME="name" TYPE="string"
					CLASSORIGIN="Service" MAXLEN="50"/>
		</GKES:CLASS>

	</GKES:MODELCLASS>

	<!-- Association Definition -->
	<GKES:MODELASSOCIATION>
		<GKES:ASSOCIATION NAME="Component"
				TYPE="CONTAINMENT" ISCORE="true" >
			<GKES:FIRSTCLASS NAME="ManagedSystemElement"
					ROLE="containSystemElement"
					MULTIPLICITY="1"/>
			<GKES:SECONDCLASS NAME="ManagedSystemElement"
					ROLE="containedBySystemElement"
					MULTIPLICITY="*"/>
		</GKES:ASSOCIATION>

		<GKES:ASSOCIATION NAME="SystemDevice"
				TYPE="CONTAINMENT" ISCORE="true" >
			<GKES:FIRSTCLASS NAME="System"
					ROLE="hasDevice"
					MULTIPLICITY="1"/>
			<GKES:SECONDCLASS NAME="LogicalDevice"
					ROLE="deviceComponentOfSystem"
					MULTIPLICITY="*"/>
		</GKES:ASSOCIATION>

		<GKES:ASSOCIATION NAME="ComponentBy"
				TYPE="CONTAINMENT" ISCORE="true" >
			<GKES:FIRSTCLASS NAME="Group"
					ROLE="containManagedElement"
					MULTIPLICITY="1"/>
			<GKES:SECONDCLASS NAME="ManagedElement"
					ROLE="containedByGroup"
					MULTIPLICITY="*"/>
		</GKES:ASSOCIATION>
